export enum Allergen {
  CELERY = "Celery",
  GLUTEN = "Gluten",
  CRUSTACEANS = "Crustaceans",
  EGGS = "Eggs",
  FISH = "Fish",
  LUPIN = "Lupin",
  LACTOSE = "Lactose",
  DAIRY = "Dairy",
  MOLLUSCS = "Molluscs",
  MUSTARD = "Mustard",
  PEANUTS = "Peanuts",
  SESAME = "Sesame seeds",
  SOYA = "Soya",
  SULFITES = "Sulfites",
  NUTS = "Tree nuts",
}
